# Benjamin BENTEKE

## AIMS SENEGAL 2019/2020

### TRAVAIL INDIVIDUEL SUR L'INTRODUCTION DE NUMPY

In [1]:
import numpy as np

In [3]:
### Creation d'un tableau
A=np.array([1,2,3])
A

array([1, 2, 3])

In [117]:
# La dimension
A.ndim

1

In [118]:
# La taille
A.shape

(3,)

In [119]:
# nombre de lignes et nombre de colonnes
A.shape[0] # Nombre de lignes
#A.shape[1] # Nombre de colonnes

3

In [127]:
### La taille d'une matrice
A.size

3

In [120]:
M=np.array([[1,2],[3,5],[0,4]])
M

array([[1, 2],
       [3, 5],
       [0, 4]])

In [121]:
# Dimension d'une matrice (c'est toujours 2 car les elements sont a_ij)
M.ndim

2

In [122]:
# le nombre de lignes et colonnes
M.shape

(3, 2)

In [123]:
# nombre de lignes et nombre de colonnes
M.shape[0] # Nombre de lignes


3

In [124]:
M.shape[1] # Nombre de colonnes

2

In [125]:
### Une matrice de dimension 3
N=np.array([[[1,2],[2,3]]])
N.ndim

3

In [128]:
### La taille d'une matrice
M.size

6

#### Remarques
Shape renvoit un type tuple.
On doit toujours mettre shape (n_lign,n_col) dans la création

### Creation de matrices specifiques

#### 1) Matrice unité

In [32]:
## I=np.eyes(taille)

In [33]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 2) Matrice remplique  de 1

In [8]:
# format general:
M=np.ones((3,2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
M=np.ones((3,2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### 3) Matrice remplie que d'un nombre quelconque

In [10]:
# format general:
M=np.full((3,2),4)
M

array([[4, 4],
       [4, 4],
       [4, 4]])

In [11]:
F=np.full((3,2),4)
F

array([[4, 4],
       [4, 4],
       [4, 4]])

#### 4) Matrice de nombres aléatoires suivant la loi normale

In [12]:
# format general:
# M=np.random.randn(shape)    moyenne=0 et ecart-type=1

### Fixation de nombres aléatoires

In [14]:
np.random.seed(20) ### C'est pour eviter les modifications c'est-à-dire controler l'aléa. 

In [15]:
N=np.random.randn(3,2)
N

array([[ 0.88389311,  0.19586502],
       [ 0.35753652, -2.34326191],
       [-1.08483259,  0.55969629]])

#### 5) Matrices nulle

In [16]:
Z=np.zeros((3,4))
Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 6) Creation de liste suivant un ordre avec pas aleatoire mais fixe /// Utile pour Matplotlib
N=np.linspace(debut,fin,quantité)

In [17]:
N=np.linspace(1,4,20)
N

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

#### 7) Creation de liste suivant un ordre avec pas prédefini /// Utile pour Matplotlib
N=np.arange(debut,fin,pas)

In [18]:
N=np.arange(1,4,1)
N

array([1, 2, 3])

#### Remarques:
linspace and arange are the constructor

# Manipulation de Tableaux

### 1) Assemblage de deux tableaux (meme dimension)

#### Fonctions hstack et vstack

In [19]:
A=np.zeros((2,2))
A

array([[0., 0.],
       [0., 0.]])

In [20]:
B=np.ones((2,2))
B

array([[1., 1.],
       [1., 1.]])

##### Assemblage horizontal: par rapport des colonnes 

In [22]:
C=np.hstack((A,B))
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

##### Assemblage vertical: par rapport des lignes

In [23]:
L=np.vstack((A,B))
L

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

#### Fonction concatenate, precisant axis remplace hstack et vstacks

In [25]:
C=np.concatenate((A,B),axis=0) ### axis=0, veut dire par rapport aux lignes
C

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [26]:
C=np.concatenate((A,B),axis=1) ### axis=1, veut dire par rapport aux colonnes
C

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

#### Fonction reshape
Elle permet de redimensionner un tableau

In [27]:
A=np.arange(2,20,2)
A

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
A.shape

(9,)

In [29]:
A.reshape((3,3))

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
A.size

9

In [31]:
K=np.array([1,2,3])
K
K.shape

(3,)

In [33]:
K=K.reshape((K.shape[0],1))
print(K)
print(K.shape)

[[1]
 [2]
 [3]]
(3, 1)


##### La methode squeeze permet d'annuler la ligne precedente

In [156]:
K=K.squeeze()
K.shape

(3,)

### La Methode Ravel
Elle permet d'aplatir un tableau en une seule dimension.

In [34]:
X=np.array([[1,2,3],[0,2,1],[0,2,3]])
X

array([[1, 2, 3],
       [0, 2, 1],
       [0, 2, 3]])

In [35]:
X=X.ravel()
X

array([1, 2, 3, 0, 2, 1, 0, 2, 3])

#### X.Flatten() = X.ravel()

In [37]:
X.flatten()

array([1, 2, 3, 0, 2, 1, 0, 2, 3])

In [38]:
#X.flat(X)

# Indexing, slicing and subsetting

#### 1) Indexing
Navigation dans un tableau. Repere d'un element selon sa position en ligne et en colonne. (le comptage commence par 0)

In [39]:
M=np.array([[1,3,4],[2,4,0],[0,5,4]])
M

array([[1, 3, 4],
       [2, 4, 0],
       [0, 5, 4]])

In [40]:
m_00=M[0,0] # Affichage de 1, 1ere ligne et 1ere colonne
m_00

1

In [41]:
m_12=M[1,2] # Affichage de 0, 1eme ligne et 2eme colone
m_12

0

In [183]:
M[:,0:2]

array([[1, 3],
       [2, 4],
       [0, 5]])

In [184]:
M[0:2,:]

array([[1, 3, 4],
       [2, 4, 0]])

In [187]:
M[0],M[1],M[2]

(array([1, 3, 4]), array([2, 4, 0]), array([0, 5, 4]))

In [188]:
M[0:2,0:2]

array([[1, 3],
       [2, 4]])

### 2) Subsetting

In [190]:
M[:,1:]

array([[3, 4],
       [4, 0],
       [5, 4]])