In [1]:
import numpy as np
import numpy.matlib

In [4]:
print(np.matlib.eye(3,4,0,dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [5]:
print(np.full((3,3),2))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [9]:
print(np.ones((4,4),dtype=int))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
print(np.random.randn(2,4))

[[ 0.93839341 -0.08095143 -0.22325797 -0.23108763]
 [ 0.06041217  1.45407944 -0.19817104 -0.13656709]]


In [6]:
print(np.matlib.rand(3,3))

[[0.14580804 0.96886906 0.63789761]
 [0.52074992 0.39232454 0.60615907]
 [0.19067911 0.13987761 0.57024888]]


In [9]:
n=np.array([[1,1],[2,1]])
print(n)
m=np.array([[0,1],[2,3]])
print(m)
print(np.dot(n,m))

[[1 1]
 [2 1]]
[[0 1]
 [2 3]]
[[2 4]
 [2 5]]


In [10]:
print(np.vdot(n,m))

8
